name: Bug Report
description: Something isn't working
labels: ["type: bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform (iOS / Android / Web)
